version: '3.7'

services:
  db:
    image: postgres:12-alpine
    volumes:
      - pg_data:/var/lib/postgresql/data/
    environment:
        POSTGRES_PASSWORD: 123456
        POSTGRES_USER: postgres
        POSTGRES_DB: postgres
  django:
    container_name: neoshop
    build:
      context: ./
      dockerfile: Dockerfile
    command:  bash -c "python /usr/src/neoshop/manage.py migrate --noinput && python /usr/src/neoshop/manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/usr/src/neoshop
    ports:
      - 8000:8000
    depends_on:
      - db
volumes:
  pg_data:
